### ISSUE TITLE
Sharing dataset

### ISSUE THREAD

**Issue by thematrixduo** [arnabgho/Contextual-RNN-GAN#3]
I think the DAT-DAR diagrammatic reasoning dataset you used is very valuable for researches in the field of machine reasoning. I just would like to ask if you could share this dataset? I am personally working on diagrammatic reasoning and therefore would like to link your method with my research.

**Comment by Ghost---Shadow** [comment]
I found it quite weird that undergraduate level human performance was `44.17%`.

I really wanted to inspect the dataset.

**Comment by vivkul** [comment]
Hi, unfortunately even after trying a lot, we couldn't get the rights from the publishers to make the question-answer data public.

**Comment by vivkul** [comment]
Hi, here is a link: https://goo.gl/HJkwny . It contains 'Abstract Reasoning Diagram Generation.zip' which is a part of the dataset we used and it doesn't belong to any publisher. I think it is better than none, and large enough for some algorithms. Also, this link contains Human_IQ_Test.zip which contains 7 problem sets used to evaluate humans. Its correct answers are in 'Abstract Reasoning Diagram Generation.zip'.
